name: Scheduled dotCMS Credential Scan

# 1. Trigger: Run daily to check for new releases
# The cron expression '0 0 * * *' means "at midnight UTC every day".
on:
  schedule:
    - cron: '0 0 * * *'
  # Allows manual triggering via the GitHub Actions UI
  workflow_dispatch:

jobs:
  scan_latest_dotcms_release:
    runs-on: ubuntu-latest
    
    env:
      TARGET_REPO: dotcms/core
      DETECTOR_REPO: ynori7/credential-detector
      SCAN_DIR: dotcms_source
    
    steps:
      - name: Install jq for JSON parsing
        # jq is required to reliably parse the latest tag from the GitHub API response
        run: sudo apt-get update && sudo apt-get install -y jq

      # 2. Get the latest dotCMS release tag using the GitHub API
      - name: Get Latest Tag
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s "https://api.github.com/repos/${{ env.TARGET_REPO }}/releases/latest" | jq -r .tag_name)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "::error::Could not find latest release tag for ${{ env.TARGET_REPO }}. Skipping scan."
            exit 1
          fi
          
          echo "Latest dotCMS tag is: $LATEST_TAG"
          # Set the tag as a job output for subsequent steps
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      # 3. Checkout the credential-detector tool
      - name: Checkout Credential Detector
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DETECTOR_REPO }}
          path: credential-detector
          
      # 4. Setup Python and install detector dependencies
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Detector Dependencies
        run: |
          pip install -r credential-detector/requirements.txt
          
      # 5. Clone the specific dotCMS version for scanning
      - name: Clone Target Repository Version
        run: |
          echo "Cloning ${{ env.TARGET_REPO }} at tag ${{ steps.get_tag.outputs.tag }}"
          # Use depth 1 to save time, and explicitly checkout the specific release tag
          git clone --depth 1 --branch ${{ steps.get_tag.outputs.tag }} https://github.com/${{ env.TARGET_REPO }}.git ${{ env.SCAN_DIR }}
          
      # 6. Run the Credential Detector
      - name: Run Credential Scan
        run: |
          echo "Starting scan of dotCMS version ${{ steps.get_tag.outputs.tag }}..."
          python credential-detector/credential_detector.py ${{ env.SCAN_DIR }}
          
      # 7. (Optional) Add steps here to handle the detector's output
      #    e.g., upload scan results as a GitHub artifact, or fail the job if credentials are found.
